In [12]:
import numpy as np

import sys
import os

module_path = os.path.join(os.getcwd(), 'modules')
sys.path.append(module_path)
from mlp import MLP, CompoundNN
from activation_functions import ReLU

In [13]:
mlp1 = MLP(6,5)
relu1 = ReLU()
mlp2 = MLP(5,4)
relu2 = ReLU()

In [14]:
nn = CompoundNN([mlp1, relu1, mlp2, relu2])

In [15]:
x = np.random.randn(1, 6) # x são os valores de entrada

In [16]:
print(relu2(mlp2(relu1(mlp1(x)))))

[[ 0.          0.          3.76710408 12.7569353 ]]


In [17]:
print(nn(x))

[[ 0.          0.          3.76710408 12.7569353 ]]


#### Teste de load and save na MLP

In [18]:
mlp1 = MLP(6,5)
mlp2 = MLP(6,5)
x = np.random.randn(1, 6)

In [19]:
print(mlp1(x))
print(mlp2(x))

[[2.26701402 2.75388002 0.87719482 2.08977105 1.94537355]]
[[-1.59118791 -0.60287212 -4.42268401 -3.55621343 -4.94581762]]


In [20]:
mlp1.save('mlp_test')
mlp2.load('trainings/mlp_test')

In [21]:
print(mlp1(x))
print(mlp2(x))

[[2.26701402 2.75388002 0.87719482 2.08977105 1.94537355]]
[[2.26701402 2.75388002 0.87719482 2.08977105 1.94537355]]


#### Teste de load and save na CompoundNN

In [22]:
mlp1 = MLP(6,5)
relu1 = ReLU()
mlp2 = MLP(5,4)
relu2 = ReLU()
nn1 = CompoundNN([mlp1, relu1, mlp2, relu2])

mlp1 = MLP(6,5)
relu1 = ReLU()
mlp2 = MLP(5,4)
relu2 = ReLU()
nn2 = CompoundNN([mlp1, relu1, mlp2, relu2])

In [23]:

x = np.random.randn(1, 6)

print(nn1(x))
print(nn2(x))

[[0.         0.47355059 0.         9.99903999]]
[[0.         0.         0.54397692 6.29269025]]


In [25]:
nn1.save('nn1')
nn2.load('trainings/nn1')

In [26]:
print(nn1(x))
print(nn2(x))

[[0.         0.47355059 0.         9.99903999]]
[[0.         0.47355059 0.         9.99903999]]


In [27]:
mlp1.backward()