In [1]:
import numpy as np

import sys
import os

module_path = os.path.join(os.getcwd(), 'modules')
sys.path.append(module_path)
from mlp import MLP, CompoundNN
from activation_functions import ReLU

In [2]:
mlp1 = MLP(6,5)
relu1 = ReLU()
mlp2 = MLP(5,4)
relu2 = ReLU()

In [3]:
nn = CompoundNN([mlp1, relu1, mlp2, relu2])

In [4]:
x = np.random.randn(1, 6) # x são os valores de entrada

In [5]:
print(relu2(mlp2(relu1(mlp1(x)))))

[[0. 0. 0. 0.]]


In [6]:
print(nn(x))

[[0. 0. 0. 0.]]


#### Teste de load and save na MLP

In [9]:
mlp1 = MLP(6,5)
mlp2 = MLP(6,5)
x = np.random.randn(1, 6)

In [10]:
print(mlp1(x))
print(mlp2(x))

[[-0.95887322  1.87496013 -4.07064903 -2.17545601  1.22781164]]
[[ 0.72077279 -2.16495184  2.88670121  0.25187097 -3.18573409]]


In [11]:
mlp1.save('mlp_test')
mlp2.load('mlp_test')

In [12]:
print(mlp1(x))
print(mlp2(x))

[[-0.95887322  1.87496013 -4.07064903 -2.17545601  1.22781164]]
[[-0.95887322  1.87496013 -4.07064903 -2.17545601  1.22781164]]


#### Teste de load and save na CompoundNN

In [13]:
mlp1 = MLP(6,5)
relu1 = ReLU()
mlp2 = MLP(5,4)
relu2 = ReLU()
nn1 = CompoundNN([mlp1, relu1, mlp2, relu2])

mlp1 = MLP(6,5)
relu1 = ReLU()
mlp2 = MLP(5,4)
relu2 = ReLU()
nn2 = CompoundNN([mlp1, relu1, mlp2, relu2])

In [14]:

x = np.random.randn(1, 6)

print(nn1(x))
print(nn2(x))

[[0.74640134 0.20526077 0.         0.        ]]
[[0.         1.35919377 1.20006706 0.64376929]]


In [15]:
nn1.save('nn1')
nn2.load('nn1')

In [16]:
print(nn1(x))
print(nn2(x))

[[0.74640134 0.20526077 0.         0.        ]]
[[0.74640134 0.20526077 0.         0.        ]]
