In [1]:
import numpy as np

import sys
import os

module_path = os.path.join(os.getcwd(), 'modules')
sys.path.append(module_path)
from mlp import MLP, CompoundNN
from activation_functions import ReLU

In [2]:
mlp1 = MLP(6,5)
relu1 = ReLU()
mlp2 = MLP(5,4)
relu2 = ReLU()

In [3]:
nn = CompoundNN([mlp1, relu1, mlp2, relu2])

In [4]:
x = np.random.randn(1, 6) # x são os valores de entrada

In [5]:
print(relu2(mlp2(relu1(mlp1(x)))))

[[0.24602493 0.03086799 0.         0.81758164]]


In [6]:
print(nn(x))

[[0.24602493 0.03086799 0.         0.81758164]]


#### Teste de load and save na MLP

In [7]:
mlp1 = MLP(6,5)
mlp2 = MLP(6,5)
x = np.random.randn(1, 6)

In [8]:
print(mlp1(x))
print(mlp2(x))

[[-3.45878874  3.30817126  5.38585563  6.16854073  0.81544675]]
[[  2.38922278  -5.34402406  -1.18189826 -10.67737612   1.18880292]]


In [9]:
mlp1.save('mlp_test')
mlp2.load('trainings/mlp_test')

In [10]:
print(mlp1(x))
print(mlp2(x))

[[-3.45878874  3.30817126  5.38585563  6.16854073  0.81544675]]
[[-3.45878874  3.30817126  5.38585563  6.16854073  0.81544675]]


#### Teste de load and save na CompoundNN

In [11]:
mlp1 = MLP(6,5)
relu1 = ReLU()
mlp2 = MLP(5,4)
relu2 = ReLU()
nn1 = CompoundNN([mlp1, relu1, mlp2, relu2])

mlp1 = MLP(6,5)
relu1 = ReLU()
mlp2 = MLP(5,4)
relu2 = ReLU()
nn2 = CompoundNN([mlp1, relu1, mlp2, relu2])

In [12]:

x = np.random.randn(1, 6)

print(nn1(x))
print(nn2(x))

[[0.         1.0108033  1.23915377 0.        ]]
[[0.         0.         0.63024569 3.1487463 ]]


In [13]:
nn1.save('nn1')
nn2.load('trainings/nn1')

In [14]:
print(nn1(x))
print(nn2(x))

[[0.         1.0108033  1.23915377 0.        ]]
[[0.         1.0108033  1.23915377 0.        ]]


In [15]:
# mlp1.backward()

In [16]:
gradout = np.random.randn(1, 4)
nn1.backward(gradout)

array([[-0.57420437, -0.00704587,  0.46274779,  1.70765271, -1.46603119,
        -2.3276824 ]])